mainMasterpiesce/mainMasterpiesce/Controllers/DoctorsInfoController.cs
using mainMasterpiesce.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Globalization;
using System.Diagnostics;
using Microsoft.Ajax.Utilities;
using static System.Net.Mime.MediaTypeNames;
using System.Drawing.Drawing2D;
using System.Drawing;
using System.Web.UI.WebControls;
using Newtonsoft.Json.Linq;
using System.Net.Http;


using System.Security.Claims;
using System.Threading.Tasks;

using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;

using System.Text.RegularExpressions;
using System.Net.Mail;
using System.Net;
using System.Web.Helpers;
using System.Web.Services.Description;
using System.Xml.Linq;
using static mainMasterpiesce.Controllers.ManageController;

namespace mainMasterpiesce.Controllers
{
    public class DoctorsInfoController : Controller
    {
        // GET: DoctorsInfo
        FindingpeaceEntities1 doc=new FindingpeaceEntities1();

       
        public ActionResult therapiestlist(string therapistName, string specializationsearch, string Male, string rating, string therapytype, string desc)
        {

            TempData["Removedata"] = "Remove";


            var avgfeedback = doc.feedbacks.GroupBy(c => c.doctorId).Select(g => new { doctorId = g.Key, avgrating = g.Average(c => c.rating) });


            foreach (var item in avgfeedback)
            {
                ViewBag.avg += item;

            }
            string url = Request.Url.AbsoluteUri;
            ViewBag.url = url;// get the absolute URL of the current request
            string[] segments = url.Split('/'); // split the URL into segments
            string lastSegment = segments[segments.Length - 1];
            string beforlast = segments[segments.Length - 2];
            ViewBag.Last = lastSegment;
            ViewBag.befLast = beforlast;
            TempData["lasrseg"] = lastSegment;


            if (TempData["swal_message"] == "Thank You for your feedback")
            {
                TempData["swal_message"] = "Thank You for your feedback";
                ViewBag.title = "info";
                ViewBag.icon = "success";
          


            }

            if (TempData["swal_message"] == "Please log in to add Feedback.")
            {

                TempData["swal_message"] = "Please log in to add Feedback.";
                ViewBag.title = "Warning";
                ViewBag.icon = "warning";
                ViewBag.redirectUrl = Url.Action("Login", "Account");

            }
               

            if (TempData["swal_message"] == "please Add Feedback before submit")
            {
                TempData["swal_message"] = "please Add Feedback before submit";
                ViewBag.title = "Warning";
                ViewBag.icon = "warning";
                ViewBag.redirectUrl = Url.Action("Login", "Account");


            }




            //var feedbackcoumt = doc.feedbacks.Where(c => c.statefeedback == 1).Count();








            var APPOINT = doc.appointments.ToList();
            


            var alldoctors = doc.doctors.Where(c => c.statedoctor == 1).ToList();
            var specialization = doc.specializations.ToList();
            int therapyTypeInt, ratingInt;
            var accepteddoctors = doc.doctors.Where(c => c.statedoctor == 1).ToList();
            if (desc != null && desc == "highest")
            {
                var highestrate = doc.doctors.Where(c => c.statedoctor == 1).OrderByDescending(c => c.ratingint).ToList();


                return View(Tuple.Create(highestrate, specialization));
            }
            else if (desc != null && desc == "lowest")
            {

                var lowestprice = doc.doctors.Where(c => c.statedoctor == 1).OrderBy(c => c.pricePerHour).ToList();
                return View(Tuple.Create(lowestprice, specialization));

            }



            if (therapistName != null)
            {
                var searchDoctor = doc.doctors.Where(c => c.doctorName.Contains(therapistName) && c.statedoctor == 1).ToList();

                return View(Tuple.Create(searchDoctor, specialization));

            }

            //male=
            if (Male != null && Male == Convert.ToString(1) && rating == null && therapytype == null)
            {

                var genderfiltering = doc.doctors.Where(c => c.Gender == true && c.statedoctor == 1).ToList();
                return View(Tuple.Create(genderfiltering, specialization));
            }
            else if (Male != null && Male == Convert.ToString(0) && rating == null && therapytype == null)
            {
                var genderfiltering0 = doc.doctors.Where(c => c.Gender == false && c.statedoctor == 1).ToList();
                return View(Tuple.Create(genderfiltering0, specialization));
            }
            //rating

            if (rating != null && therapytype == null && Male == null)
            {
                int ratingdecimalradio = Convert.ToInt16(rating);
                var ratingdoctor = doc.doctors.Where(c => c.statedoctor == 1 && c.ratingint == ratingdecimalradio)
                                             .ToList();

                return View(Tuple.Create(ratingdoctor, specialization));








       






            }

            if (Male == null && rating == null && int.TryParse(therapytype, out therapyTypeInt))
            {
                var therapyfiltering = doc.doctors.Where(c => c.specializationId == therapyTypeInt && c.statedoctor == 1).ToList();
                return View(Tuple.Create(therapyfiltering, specialization));

            }
            //1 all exist and female


            if (int.TryParse(therapytype, out therapyTypeInt) && int.TryParse(rating, out ratingInt) && Male == Convert.ToString(0))
            {
                var generalfiltering = doc.doctors.Where(c => c.specializationId == therapyTypeInt && c.ratingint == ratingInt && c.Gender == false && c.statedoctor == 1).ToList();
                return View(Tuple.Create(generalfiltering, specialization));
            }
            //all exist and maleALL
            if (int.TryParse(therapytype, out therapyTypeInt) && int.TryParse(rating, out ratingInt) && Male == Convert.ToString(1))
            {
                var generalfiltering = doc.doctors.Where(c => c.specializationId == therapyTypeInt && c.ratingint == ratingInt && c.Gender == true && c.statedoctor == 1).ToList();
                return View(Tuple.Create(generalfiltering, specialization));
            }
            //2exist gender and thyarapytyprgender=0
            if (Male == Convert.ToString(0) && int.TryParse(therapytype, out therapyTypeInt) && rating == null)
            {

                var filtergendtherapy0 = doc.doctors.Where(c => c.Gender == false && c.specializationId == therapyTypeInt && c.statedoctor == 1).ToList();

                return View(Tuple.Create(filtergendtherapy0, specialization));


            }
            //2exist gender and thyarapytyprgender=1
            if (Male == Convert.ToString(1) && int.TryParse(therapytype, out therapyTypeInt) && rating == null)
            {

                var filtergendtherapy1 = doc.doctors.Where(c => c.Gender == true && c.specializationId == therapyTypeInt && c.statedoctor == 1).ToList();

                return View(Tuple.Create(filtergendtherapy1, specialization));


            }   //2exist therapytype and rating...
            if (Male == null && int.TryParse(therapytype, out therapyTypeInt) && int.TryParse(rating, out ratingInt))
            {

                var filterratingtherapy = doc.doctors.Where(c => c.ratingint == ratingInt && c.specializationId == therapyTypeInt && c.statedoctor == 1).ToList();

                return View(Tuple.Create(filterratingtherapy, specialization));


            }
            //2exist gender and rating=0
            if (Male == Convert.ToString(0) && therapytype == null && int.TryParse(rating, out ratingInt))
            {

                var filtergendrating0 = doc.doctors.Where(c => c.Gender == false && c.ratingint == ratingInt && c.statedoctor == 1).ToList();

                return View(Tuple.Create(filtergendrating0, specialization));


            }
            //2exist gender and rating=1
            if (Male == Convert.ToString(1) && therapytype == null && int.TryParse(rating, out ratingInt))
            {

                var filtergendrating1 = doc.doctors.Where(c => c.Gender == true && c.ratingint == ratingInt && c.statedoctor == 1).ToList();

                return View(Tuple.Create(filtergendrating1, specialization));


            }

            if (TempData["LoadMore"] == null)
            {


                TempData["more"] = 10;

            }else if (TempData["LoadMore"] == "LoadMore")
            {


                TempData["more"] = 20;
            }


            return View(Tuple.Create(alldoctors, specialization));
        }





        public ActionResult LoadMore()
        {
            TempData["LoadMore"] = "LoadMore";

     

           return RedirectToAction("therapiestlist");
        }





        public ActionResult alldoctors(string therapistName, string specializationsearch,string Male,string rating,string therapytype,string desc)
        {
            var avgfeedback = doc.feedbacks.GroupBy(c => c.doctorId).Select(g => new { doctorId = g.Key, avgrating = g.Average(c => c.rating) });

            foreach (var item in avgfeedback)
            {
                ViewBag.avg += item;
            }



            var alldoctors = doc.doctors.Where(c=>c.statedoctor==1).ToList();
            var specialization = doc.specializations.ToList();
            int therapyTypeInt, ratingInt;
            var accepteddoctors=doc.doctors.Where(c=>c.statedoctor==1).ToList();
       if(desc!=null&&desc=="highest")
            {

mainMasterpiesce/mainMasterpiesce/Views/DoctorsInfo/ChangePasswordpatient.cshtml
@model Tuple<List<mainMasterpiesce.Models.patient>, List<mainMasterpiesce.Models.appointment>>







<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.6/dist/sweetalert2.min.css">

@{
    ViewBag.Title = "ChangePasswordpatient";
    Layout = "~/Views/Shared/_patientprofile.cshtml";
}



@using (Html.BeginForm("ChangePassword", "Manage", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Change Password Form</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="row mb-3">
        <label for="currentPassword"
               class="col-md-4 col-lg-3 col-form-label">Current Password</label>
        <div class="col-md-8 col-lg-9">
            <input name="OldPassword"
                   type="password"
                   class="form-control"
                   id="currentPassword" required />
        </div>
    </div>
    <div class="row mb-3">
        <label for="NewPassword"
               class="col-md-4 col-lg-3 col-form-label">New Password</label>
        <div class="col-md-8 col-lg-9">
            <input name="newpassword"
                   type="password"
                   class="form-control"
                   id="newPassword" required />
        </div>
    </div>
    <div class="row mb-3">
        <label for="renewPassword"
               class="col-md-4 col-lg-3 col-form-label">Re-enter New Password</label>
        <div class="col-md-8 col-lg-9" >
            <input name="ConfirmPassword"
                   type="password"
                   class="form-control"
                   id="renewPassword" required />
        </div>
    </div>
    <div class="text-center">
        <button type="submit" class="btn btn-primary">
            Change Password
        </button>
    </div>
}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.6/dist/sweetalert2.all.min.js"></script>


@if (TempData["swal_message"] == "You are Password has been changed Successfully")
{
    <script>
        Swal.fire({
            title: "@ViewBag.title",
            text: "@TempData["swal_message"]",
            icon: "@ViewBag.icon",

            allowOutsideClick: false, // prevent clicking outside the dialog to close it
            allowEscapeKey: false // prevent pressing the escape key to close it
        }).then(function () {
            window.location.href ="/DoctorsInfo/patientProfile";
        });
    </script>
}


@if (TempData["swal_message"] == "Unfourtunitly there is something wrong please try again")
{
    <script>
        Swal.fire({
            title: "@ViewBag.title",
            text: "@TempData["swal_message"]",
            icon: "@ViewBag.icon",

            allowOutsideClick: false, // prevent clicking outside the dialog to close it
            allowEscapeKey: false // prevent pressing the escape key to close it
        }).then(function () {
            window.location.href = location.pathname;
        });
    </script>
}

mainMasterpiesce/mainMasterpiesce/Views/DoctorsInfo/Profilesetting.cshtml
@using System


@model Tuple<List<mainMasterpiesce.Models.patient>, List<mainMasterpiesce.Models.appointment>>


@{
    ViewBag.Title = "Profilesetting";
    Layout = "~/Views/Shared/_patientprofile.cshtml";
}






<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.6/dist/sweetalert2.min.css">

<div class="col-md-7 col-lg-8 col-xl-9">
    <div class="card">
        <div class="card-body">

            <!-- Profile Settings Form -->
            @using (Html.BeginForm("Edit", "DoctorsInfo", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="row form-row">
                    <div class="col-12 col-md-12">
                        <div class="form-group">
                            <div class="change-avatar">
                                <div class="profile-img">

                                </div>
                                <div class="upload-img">
                                    <div class="change-photo-btn">
                                        <span><i class="fa fa-upload"></i> Upload Photo</span>
                                        <input type="file" class="upload" name="profpic">
                                    </div>
                                    <small class="form-text text-muted">
                                        Allowed JPG, GIF or PNG. Max
                                        size of 2MB
                                    </small>
                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="col-12 col-md-6">
                        <div class="form-group">
                            <label>User Name</label>
                            <input type="text" class="form-control" value="@Model.Item1[0].patientName" name="userName">
                        </div>
                    </div>
                    <div class="col-12 col-md-6">
                        <div class="form-group">
                            <label>Email ID</label>
                            <input type="text" class="form-control" value="@Model.Item1[0].AspNetUser.Email" name="Email">
                        </div>
                    </div>

                    <div class="col-12 col-md-6">
                        <div class="form-group">
                            <label>Date of Birth</label>
                            @*@Html.TextBoxFor(model => model.Item1[0].birthday, "{0:yyyy-MM-dd}", new { @class = "form-control" })*@

                            @{

                                var birthday = @Model.Item1[0].birthday;

                            }
                            @*<input type="text" class="form-control" value=" @Convert.ToDateTime(birthday).ToString("dd-MM-yyyy")" name="birthday" id="mainbirth">*@

                            <input type="text" class="form-control" value="@birthday.Value.ToString("dd/MM/yyyy")" name="birthday" />

                            @*<input type="hidden" value="@Convert.ToDateTime(birthday).ToString("dd-MM-yyyy")" id="inptbirth" />*@


                        </div>
                    </div>

                    <div class="col-12 col-md-6">
                        <div class="form-group">
                            <label>Phone No.</label>
                            <input type="text" class="form-control" value="@Model.Item1[0].AspNetUser.PhoneNumber" name="phone" oninput="CardName(this)">
                        </div>
                    </div>

                    @{string[] locat = Model.Item1[0].locationdetails.Split(',');

                    }

                    <div class="col-12 col-md-6">
                        <div class="form-group">
                            <label>Country</label>
                            <select id="countriesDropdown" class="form-control" name="country" value="@locat[0]">




                                <option value="">@locat[0]</option>




                            </select>
                        </div>
                    </div>
                    <div class="col-12 col-md-6">
                        <div class="form-group">
                            <label>City</label>

                            <input type="text" class="form-control" value="@locat[1]" name="city">
                        </div>
                    </div>

                    <div class="submit-section">
                        <button type="submit" class="btn btn-primary submit-btn">Save Changes</button>
                    </div>

                    <!-- /Profile Settings Form -->

                </div>
            }
        </div>
        <!-- Footer -->


        <script>






        </script>
    </div>


</div>







<script>
        var birth = document.getElementById("inptbirth").value

        document.getElementById("mainbirth").value=birth;
        console.log(document.getElementById("inptbirth").value);
    const countriesApiUrl = 'https://api.teleport.org/api/countries/';

    // Get a reference to the dropdown list element
    const countriesDropdown = document.getElementById('countriesDropdown');

    fetch(countriesApiUrl)
        .then(response => response.json())
        .then(data => {
            // Loop through the list of countries and add each country name to the dropdown list
            data._links['country:items'].forEach(country => {
                const option = document.createElement('option');
                option.value = country.href;
                option.text = country.name;
                countriesDropdown.appendChild(option);
            });
        })
        .catch(error => console.error(error));


    console.log("fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff")




    console.log(@Model.Item1[0].locationdetails.Split(',')[0])






    function CardName(input) {

        if (input.value.length > 17) {
            input.value = input.value.slice(0, 17);
        }
        if (isNaN(input.value)) {
            // Prevent non-numeric characters from being entered
            input.value = input.value.replace(/[^0-9]/g, '');
        }
        if (input.value.length < 10) {
            // Disable the submit button
            document.getElementById("reg").disabled = true;
            // Or display an error message
            document.getElementById("error_phone").textContent = "this field should be at least 10 digits";
        } else {
            // Enable the submit button
            document.getElementById("reg").disabled = false;
            // Clear the error message
            document.getElementById("error_phone").textContent = "";
        }
    }


</script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.6/dist/sweetalert2.all.min.js"></script>
@if (TempData["swal_message"] == "Your information has been updated successfully.")
{
    <script>
        Swal.fire({
            title: "@ViewBag.title",
            text: "@TempData["swal_message"]",
            icon: "@ViewBag.icon",

             allowOutsideClick: false, // prevent clicking outside the dialog to close it
            allowEscapeKey: false // prevent pressing the escape key to close it


        }).then(function () {
            window.location.href = "Profilesetting";

        });;
    </script>
}

mainMasterpiesce/mainMasterpiesce/Views/DoctorsInfo/_comment.cshtml
@{
    var feedback = Model.feedback;
    var doctor = Model.doctor;

}










@using (Html.BeginForm("AddFeedback", "DoctorsInfo"))
{
    <div class="form-group">
        <label>Review</label>
        <div class="star-rating">
            <input id="star-5" type="radio" name="rating" value="5">
            <label for="star-5" title="5 stars">
                <i class="active fa fa-star"></i>
            </label>
            <input id="star-4" type="radio" name="rating" value="4">
            <label for="star-4" title="4 stars">
                <i class="active fa fa-star"></i>
            </label>
            <input id="star-3" type="radio" name="rating" value="3">
            <label for="star-3" title="3 stars">
                <i class="active fa fa-star"></i>
            </label>
            <input id="star-2" type="radio" name="rating" value="2">
            <label for="star-2" title="2 stars">
                <i class="active fa fa-star"></i>
            </label>
            <input id="star-1" type="radio" name="rating" value="1">
            <label for="star-1" title="1 star">
                <i class="active fa fa-star"></i>
            </label>
        </div>
    </div>

    <div class="form-group">
        <label>Title of your review</label>
        <input class="form-control" type="text"
               placeholder="If you could say it in one sentence, what would you say?" name="title">
    </div>
    <div class="form-group">
        <label>Your review</label>
        <textarea id="review_desc" maxlength="100" class="form-control" name="yourfeedback"></textarea>

        <div class="d-flex justify-content-between mt-3">
            <small class="text-muted">
                <span id="chars">100</span> characters
                remaining
            </small>
        </div>
    </div>
    <hr>
    <div class="form-group">
        <div class="terms-accept">
            <div class="custom-checkbox">
                <input type="checkbox" id="terms_accept">
                <label for="terms_accept">
                    I have read and accept <a href="#">
                        Terms
                        &amp; Conditions
                    </a>
                </label>
            </div>
        </div>
    </div>
    <div class="submit-section">

        <button type="submit" style="background-color: #20BBBD" class="btn btn-primary submit-btn" name="ADD">Add Review</button>
        <input type="hidden" name="doctorId" value="@Model.doctor.Id">
    </div>
}