mainMasterpiesce/mainMasterpiesce/Models/transactionsdoctor.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mainMasterpiesce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transactionsdoctor
    {
        public int transDoctorId { get; set; }
        public Nullable<int> doctorId { get; set; }
        public string transactiontype { get; set; }
        public Nullable<double> amount { get; set; }
        public string paymentmethod { get; set; }
        public Nullable<System.DateTime> transactionDate { get; set; }
        public string status { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> Tansactiontime { get; set; }
        public string DOctorName { get; set; }
    
        public virtual doctor doctor { get; set; }
    }
}

mainMasterpiesce/mainMasterpiesce/Controllers/transactionsdoctorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using mainMasterpiesce.Models;
using Microsoft.Ajax.Utilities;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Hosting;
using Hangfire;
using Hangfire.SqlServer;
using Lw.Data.Entity;
using Lw.Data;

namespace mainMasterpiesce.Controllers
{
    [Authorize(Roles = "Admin")]
    public class transactionsdoctorsController : Controller
    {
        public IDbContext DbContext { get; set; }

        private FindingpeaceEntities1 db = new FindingpeaceEntities1();

        // GET: transactionsdoctors
        [AllowAnonymous]
        public ActionResult DoctorTransaction(string search,string Send)
        {
            if (TempData["list"] == null)
            {


                TempData["list"] = "Acceptlist";
            }






            //DateTime transcatedate = DateTime.ParseExact(DateTime.Now.ToString("h:mm ttdd/MM"), "h:mm ttdd/MM", CultureInfo.InvariantCulture);

            DateTime transactionDate = DateTime.Now;
            //transactionDate.DayOfWeek == DayOfWeek.Monday && transactionDate.Hour == 18
            if (true)
            {
          
       

                var doctorInfo = db.appointments
    .Where(a => a.confirmappointment == 0)
    .Select(a => new { a.doctor.doctorId, a.doctor.doctorName })
    .DistinctBy(a => a.doctorId)
    .ToList();
                var doctorAppointmentSum = db.appointments
               .Where(a => a.confirmappointment == 0)
               .GroupBy(a => a.doctorId)
               .Select(g => new { DoctorId = g.Key, TotalAppointmentPrice = g.Sum(a => a.apointmentprice) })
               .ToList();

                //ViewBag.DoctorNames = string.Join(",", doctorNames);

                var Isexist=db.transactionsdoctors.Where(c=>c.status!="2").ToList();
                List<string> doctorIdExist = new List<string>();
                string doctorIdExistString = "";
                foreach (var item in Isexist)
                {
                    doctorIdExist.Add(item.doctorId.ToString());
                    doctorIdExistString = string.Join(",", doctorIdExist);

                }



            

                foreach (var doctor in doctorInfo)
                {

                    if (!doctorIdExist.Contains(doctor.doctorId.ToString()))
                    {


                 
                      var transactionDoctor = new transactionsdoctor
                    {
                        DOctorName = doctor.doctorName,
                        doctorId = doctor.doctorId,
                        amount=0,
                        status = "1",
                       

                };

                    // Add the new transaction doctor to the database
                    db.transactionsdoctors.Add(transactionDoctor);
              
                db.SaveChanges();
                    }
                }
                //var doctorr = db.doctors.FirstOrDefault(c => c.doctorId == docId);
                //doctorr.statedoctor = 1;

                //db.Entry(doctorr).State = EntityState.Modified;

                foreach (var appointment in doctorAppointmentSum)
                {


                    var transactionDoctor = db.transactionsdoctors.FirstOrDefault(c => c.doctorId == appointment.DoctorId&&c.status!="2");

                    transactionDoctor.amount = appointment.TotalAppointmentPrice * .95+ transactionDoctor.amount;
                    db.Entry(transactionDoctor).State = EntityState.Modified;

                    //    var transactionDoctor = new transactionsdoctor
                    //    {
                    //       amount=appointment.TotalAppointmentPrice*.95,



                    //};

                    // Add the new transaction doctor to the database
                    //db.transactionsdoctors.Add(transactionDoctor);
                }





                var doc = db.appointments.Where(c => c.confirmappointment == 0).ToList();

                foreach (var item in doc)
                {

                   item.confirmappointment = 1;//when I say 1 the info reach transactiodoc table without money



                 
                }

                // Save changes to the database
                db.SaveChanges();



            }
            //var checktime = db.transactionsdoctors.OrderBy(c=>c.Tansactiontime).FirstOrDefault();
            var checktime = db.transactionsdoctors.OrderByDescending(c=>c.Tansactiontime).FirstOrDefault();
            if (checktime != null)
            {

                TimeSpan? timeDifference = DateTime.Now - checktime.Tansactiontime;
                ViewBag.DEFER = timeDifference.Value.Days + (timeDifference.Value.Hours / 24);

                ViewBag.exact = checktime.Tansactiontime.Value.Date.ToString("dd/MM/yyyy");
            }




                if (Send != null)
            {

                TempData["list"] = "rejectlisttrans";
               
                int countapoint = 0;


                var doctorAppointmentSum = db.appointments
                 .Where(a => a.confirmappointment == 1)
                 .GroupBy(a => a.doctorId)
                 .Select(g => new { DoctorId = g.Key, TotalAppointmentPrice = g.Sum(a => a.apointmentprice) })
                 .ToList();


                if (countapoint > 0 && ViewBag.DEFER < 7)
                {
                    TempData["list"] = "Rejectlist";
                    TempData["swal_message"] = "Please note that transactions can only be initiated after a minimum of 7 days from your last transaction for optimal care. Thank you for your understanding.";
                    ViewBag.title = "Warning";
                    ViewBag.icon = "warning";
                    

               


                }


                foreach (var appointment in doctorAppointmentSum)
                {
                    if (ViewBag.DEFER < 7)
                    {
                        break;
                    }




                    countapoint++;
                    var transaction = db.transactionsdoctors
                        .SingleOrDefault(t => t.status == "1" && t.doctorId == appointment.DoctorId);

                    if (transaction != null)
                    {
                        //transaction.amount = appointment.TotalAppointmentPrice*.95;
                        transaction.Tansactiontime = DateTime.Now;
                        transaction.status = "2";
                    }

                    var appconfirm = db.appointments.Where(c => c.confirmappointment == 1).ToList();







                    foreach (var item in appconfirm)
                    {
                      


                        item.confirmappointment = 2;

                    }


                }







                if (countapoint > 0&& ViewBag.DEFER>=7)
                {

                    TempData["swal_message"] = $" We are delighted to inform you that the transaction for the doctors has been successfully completed. Thank you for your cooperation and promptness in this process";

                    ViewBag.title = "success";
                    ViewBag.icon = "success";


                    db.SaveChanges();
                }
                else if(countapoint ==0)
                {
                    TempData["swal_message"] = "We would like to inform you that there are no pending transactions to be sent at this time. If you have any questions or require further assistance, please do not hesitate to contact us. Thank you for your attention to this matter";
                    ViewBag.title = "Warning";
                    ViewBag.icon = "warning";

                }

     

           

            }

            // Add 7 days to the appointmentTime variable
            //transcatedate = transcatedate.AddDays(7);






                var transactionsdoctors = db.transactionsdoctors.Include(t => t.doctor);

            if (!string.IsNullOrEmpty(search))
            {
                var searchh = db.transactionsdoctors.Where(c => c.doctor.doctorName.Contains(search) ).ToList();

                return View(searchh);

            }
            else
            {
                return View(transactionsdoctors.ToList());

            }


  

        }









        public ActionResult Acceptlist([Bind(Include = "status")] transactionsdoctor transacytiondoc, string Accept)
        {

            TempData["list"] = "Acceptlisttrans";

            return RedirectToAction("DoctorTransaction", new { listType = "Acceptlisttrans" });

        }
        public ActionResult Rejectlist([Bind(Include = "status")] transactionsdoctor transactiondoc, string Accept)
        {

            TempData["list"] = "Rejectlisttrans";


            return RedirectToAction("DoctorTransaction", new { listType = "rejectlisttrans" });


        }










        // GET: transactionsdoctors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            transactionsdoctor transactionsdoctor = db.transactionsdoctors.FirstOrDefault(c=>c.doctorId==id);
            if (transactionsdoctor == null)
            {
                return HttpNotFound();
            }
            return View(transactionsdoctor);
        }

        // GET: transactionsdoctors/Create
        public ActionResult Create()
        {
            ViewBag.doctorId = new SelectList(db.doctors, "doctorId", "Id");
            return View();
        }

        // POST: transactionsdoctors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]

mainMasterpiesce/mainMasterpiesce/Views/transactionsdoctors/Create.cshtml
@model mainMasterpiesce.Models.transactionsdoctor

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminDashBoard.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>transactionsdoctor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.doctorId, "doctorId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("doctorId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.doctorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.transactiontype, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.transactiontype, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.transactiontype, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.paymentmethod, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.paymentmethod, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.paymentmethod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.transactionDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.transactionDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.transactionDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tansactiontime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tansactiontime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tansactiontime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

mainMasterpiesce/mainMasterpiesce/Views/transactionsdoctors/Delete.cshtml
@model mainMasterpiesce.Models.transactionsdoctor

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminDashBoard.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>transactionsdoctor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.transactiontype)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.transactiontype)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.paymentmethod)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.paymentmethod)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.transactionDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.transactionDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tansactiontime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tansactiontime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.doctor.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.doctor.Id)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

mainMasterpiesce/mainMasterpiesce/Views/transactionsdoctors/DoctorTransaction.cshtml
@model IEnumerable<mainMasterpiesce.Models.transactionsdoctor>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminDashBoard.cshtml";
}


<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.6/dist/sweetalert2.min.css">
<p>
    @Html.ActionLink("Create New", "Create")
</p>








@{
    string test; }


@if (TempData["list"] == "rejectlisttrans")
{
    test = "1";
}
else
{
    test = "2";

}

@{
    string q = Request.QueryString["listType"];


    if (q == "rejectlisttrans")
    {

        test = "1";
    }


    if (q == "Acceptlisttrans")
    {

        test = "2";
    }
}

@if (test == "2")
{
    @section Content {
        <form action="DoctorTransaction">
            <input type="text" class="form-control" placeholder="Search here" name="search">
            <button class="btn" type="submit"><i class="fa fa-search"></i></button>
        </form>
    }

}



<div class="page-wrapper">
    <div class="content container-fluid">

        <!-- Page Header -->
        <div class="page-header">
            <div class="row">
                <div class="col-sm-12">
                    <a> <h3 class="page-title" onclick="toggleDisplay('upcoming-appointments')"> Doctor Transactions</h3></a>
                    <ul class="breadcrumb">
                    </ul>



                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">


                <!-- Recent Orders -->
                <div class="card">
                    <div class="card-body">
                        @if (ViewBag.DoctorNames != null)
                        {
                            foreach (var name in ViewBag.DoctorNames.Split(','))
                            {
                                <p>@name</p>
                            }
                        }
                        <div class="table-responsive">
                            <div id="upcoming-appointments" class="appointments">
                                <table class="datatable table table-hover table-center mb-0">
                                    <thead>
                                        <tr>
                                            <th>Invoice Number</th>
                                            <th>Doctor ID</th>
                                            <th>Doctor Name</th>
                                            <th>Total Amount</th>
                                            <th>Status</th>
                                            <th class="text-center">Transaction Time</th>
                                            <th class="text-right">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model.Where(c => c.status == test))
                                        {


                                            <tr>
                                                <td><a href="invoice.html">#IN00 @item.transDoctorId</td>
                                                <td>#PT00 @item.doctorId</td>
                                                <td>
                                                    <h2 class="table-avatar">
                                                        <a href="profile.html" class="avatar avatar-sm mr-2"><img class="avatar-img rounded-circle" src="@Url.Content(@item.doctor.picdoctor)" alt="@item.doctor.picdoctor"></a>
                                                        <a href="profile.html">@item.doctor.doctorName</a>
                                                    </h2>
                                                </td>
                                                <td>@item.amount JD</td>

                                                <td class="text-center">

                                                    @if (item.status == "1")
                                                    {


                                                        <span class="badge badge-pill bg-danger-light">Pending</span>
                                                    }
                                                    else if (item.status == "2")
                                                    {

                                                        <span class="badge badge-pill bg-success inv-badge">Paid</span>
                                                    }

                                                </td>
                                                <td>

                                                    @if (item.Tansactiontime.HasValue)
                                                    {

                                                        @item.Tansactiontime.Value.ToString("dd-MM-yyyy")

                                                    }
                                                    else
                                                    {
                                                        <p>Not Sending Yet</p>
                                                    }

                                                </td>
                                                <td class="text-right">
                                                    <div class="actions">
                                                        @if (test == "1")
                                                        {

                                                            @Html.ActionLink("Details", "Details", new { id = item.doctorId, listType = "rejectlisttrans" }, new { @class = "btn btn-info" })


                                                        }
                                                        else
                                                        {

                                                            @Html.ActionLink("Details", "Details", new { id = item.doctorId }, new { @class = "btn btn-info" })

                                                        }





                                                    </div>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                                @if (test == "1")
                                {

                                    <p>Last transaction was<strong> @ViewBag.DEFER</strong>  Days ago at @ViewBag.exact   </p>

                                    <p>you can't transcate before <strong>7</strong> Days from last transaction</p>
                                }





                                @using (Html.BeginForm("DoctorTransaction", "transactionsdoctors", FormMethod.Post))
                                {


                                    if (test == "1")
                                    {
                                        <input type="submit" name="Send" class="btn btn-info" value="Send" />

                                    }



                                }



                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.6/dist/sweetalert2.all.min.js"></script>
            @if (TempData["swal_message"] == $" We are delighted to inform you that the transaction for the doctors has been successfully completed. Thank you for your cooperation and promptness in this process")
            {
                <script>
        Swal.fire({
            title: "@ViewBag.title",
            text: "@TempData["swal_message"]",
            icon: "@ViewBag.icon",

             allowOutsideClick: false, // prevent clicking outside the dialog to close it
            allowEscapeKey: false // prevent pressing the escape key to close it


        }).then(function () {
            window.location.href = "/transactionsdoctors/DoctorTransaction";

        });;
                </script>
            }




            @if (TempData["swal_message"] == "We would like to inform you that there are no pending transactions to be sent at this time. If you have any questions or require further assistance, please do not hesitate to contact us. Thank you for your attention to this matter")
            {
                <script>
        Swal.fire({
            title: "@ViewBag.title",
            text: "@TempData["swal_message"]",
            icon: "@ViewBag.icon",

             allowOutsideClick: false, // prevent clicking outside the dialog to close it
            allowEscapeKey: false // prevent pressing the escape key to close it


        }).then(function () {
            window.location.href = "/transactionsdoctors/DoctorTransaction?listType=rejectlisttrans";

        });;
                </script>
            }



            @if (TempData["swal_message"] == "Please note that transactions can only be initiated after a minimum of 7 days from your last transaction for optimal care. Thank you for your understanding.")
            {
                <script>
        Swal.fire({
            title: "@ViewBag.title",
            text: "@TempData["swal_message"]",
            icon: "@ViewBag.icon",

             allowOutsideClick: false, // prevent clicking outside the dialog to close it
            allowEscapeKey: false // prevent pressing the escape key to close it


        }).then(function () {
            window.location.href = "/transactionsdoctors/DoctorTransaction?listType=rejectlisttrans";

        });;
                </script>
            }

mainMasterpiesce/mainMasterpiesce/Views/transactionsdoctors/Edit.cshtml
@model mainMasterpiesce.Models.transactionsdoctor

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminDashBoard.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>transactionsdoctor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.transDoctorId)

        <div class="form-group">
            @Html.LabelFor(model => model.doctorId, "doctorId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("doctorId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.doctorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.transactiontype, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.transactiontype, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.transactiontype, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.paymentmethod, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.paymentmethod, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.paymentmethod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.transactionDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.transactionDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.transactionDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tansactiontime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tansactiontime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tansactiontime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>