mainMasterpiesce/mainMasterpiesce/Controllers/DoctorEnrollingController.cs
using mainMasterpiesce.Models;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Diagnostics;
using System.Dynamic;
using System.Linq;
using System.Net.Http.Headers;
using System.Net.Http;
using System.Security.Principal;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;


using System.Text.Json;
using System.IdentityModel.Tokens.Jwt;
using Microsoft.IdentityModel.Tokens;
using System.Globalization;
using System.Web.UI.WebControls;
using Newtonsoft.Json.Linq;
using System.Net.Mail;
using System.Net;
using Microsoft.Owin;

namespace mainMasterpiesce.Controllers
{
    [Authorize(Roles = "doctor")]
    public class DoctorEnrollingController : Controller
    {
       
        //public ActionResult STDform([Bind(Include = "Student_ID,Id,Name,Email,Password,NationalNum,Grad,Pic,Status,PhoneNumber,BirthFile,PersonalIdFile,CertificateFile,Gender,Major_ID,Wallet")] Student student, HttpPostedFileBase Pic1, HttpPostedFileBase PersonalIdFile1, HttpPostedFileBase CertificateFile1, HttpPostedFileBase BirthFile1)
       FindingpeaceEntities1 db=new FindingpeaceEntities1();
        // GET: DoctorEnrolling
        [Authorize(Roles = "doctor")]
     
        public ActionResult EnrollDoctor()
        {



            if (TempData["compltesubmitting"] == "compltesubmitting")
            {
                TempData["swal_message"] = $"please complete your request in this form";
                ViewBag.title = "Warning";
                ViewBag.icon = "warning";


            }

            if (TempData["compltesubmitting"] == "waituntilaccept")
            {
                TempData["swal_message"] = "Dear Doctor,Please be advised that your documentation is currently being reviewed by our team. Once your documentation has been accepted, you will receive an email from us confirming your acceptance.Thank you for your patience and we wish you the best of luck.";
                ViewBag.title = "Warning";
                ViewBag.icon = "warning";



            }

            var mainId=User.Identity.GetUserId();
            dynamic data = new ExpandoObject();

            var specializations = db.specializations.ToList();
            var doct=db.doctors.Where(c=>c.Id==mainId).ToList();

         

          
          
            data.Specializations = specializations;
            data.doc = doct;
            //data.doctor = doctors;

            return View(data);


            
        }


        public ActionResult sendmassage()
        {
            //if (TempData["compltesubmitting"] == "compltesubmitting")
            //{
            //    TempData["swal_message"] = $"please complete your request in this form";
            //    ViewBag.title = "Warning";
            //    ViewBag.icon = "Warning";


            //}

            //if (TempData["compltesubmitting"] == "waituntilaccept")
            //{
            //    TempData["swal_message"] = "Dear Doctor,Please be advised that your documentation is currently being reviewed by our team. Once your documentation has been accepted, you will receive an email from us confirming your acceptance.Thank you for your patience and we wish you the best of luck.";
            //    ViewBag.title = "Warning";
            //    ViewBag.icon = "Warning";



            //}

        

            return RedirectToAction("EnrollDoctor");



        }




        [HttpPost]
        public ActionResult EnrollDoctor([Bind(Include = "Id,locationdoctor,doctorName,email,phoneNumber,qualiification,specialization,startedate,idCardfile,picdoctor,certificationfile,PersonalIdFile,CertificateFile,birthfile,specializationId,statedoctor,earningDoctortotal,AmountsDue,IBAN,Gender,infodoctor,pricePerHour,ratingdoctor,ratingint")] doctor doctorr, string location, string locationLink, string price, string qualif, string Iban, string exp, string info, int specializationId,string yeargrad,string University,string edu, HttpPostedFileBase PersonalIdFile1, HttpPostedFileBase Certification, HttpPostedFileBase BirthFile1, HttpPostedFileBase ExperienceFile1)
        {
           
            var doctorId = User.Identity.GetUserId();
            var doctor = db.doctors.FirstOrDefault(d => d.Id == doctorId);
            var specializ = db.specializations.ToList();
            ViewBag.special=specializ;
            dynamic data = new ExpandoObject();

            var specializations = db.specializations.ToList();
            var doct = db.doctors.Where(c=>c.Id==doctorId).ToList();
            data.Specializations = specializations;
            data.doc = doct;
            if (ModelState.IsValid)
            {
                try
                {


             
                if (PersonalIdFile1 != null)
                {
                    //string fileName = Path.GetFileName(image.FileName);
                    string path = Server.MapPath("~/FormalFile/") + PersonalIdFile1.FileName;
                    PersonalIdFile1.SaveAs(path);
                    doctor.idCardfile = PersonalIdFile1.FileName;
                }

                if (Certification != null)
                {
                    //string fileName = Path.GetFileName(cv.FileName);
                    string path = Server.MapPath("~/FormalFile/") + Certification.FileName;
                    Certification.SaveAs(path);
                    doctor.certificationfile = Certification.FileName;
                }
                if (ExperienceFile1 != null)
                {
                    //string fileName = Path.GetFileName(cv.FileName);
                    string path = Server.MapPath("~/FormalFile/") + ExperienceFile1.FileName;
                    ExperienceFile1.SaveAs(path);
                    doctor.experience = ExperienceFile1.FileName;
                }

                if (BirthFile1 != null)
                {
                    //string fileName = Path.GetFileName(cv.FileName);
                    string path = Server.MapPath("~/FormalFile/") + BirthFile1.FileName;
                    BirthFile1.SaveAs(path);
                    doctor.birthfile = BirthFile1.FileName;
                    }
                }
                catch(Exception ex)
                {


                }



                var SPECIALIZATIONNAME = db.specializations.FirstOrDefault(C => C.specializationId == specializationId).namespecialization;
                doctor.pricePerHour = Convert.ToInt16(price);
                doctor.qualiification = qualif;
                doctor.locationdoctor = doctor.locationdoctor+'_' + locationLink;
                doctor.specialization= SPECIALIZATIONNAME;
                doctor.infodoctor = info;
                doctor.IBAN = Iban;
                doctor.AspNetUser.EmailConfirmed= true;
                doctor.addresss = location;
                doctor.educationdetails = edu + '_' + University + '_' + yeargrad;
                if (specializationId != null)
                {

                    doctor.specializationId = specializationId;
                }


                ViewBag.doctorname = doctor.doctorName;

                string[] nameParts = Regex.Replace(User.Identity.Name, "[^a-zA-Z]+", " ").Split(' ');
                string firstName =nameParts[0];

                var docemail = db.doctors.FirstOrDefault(c => c.Id == doctorId).email;
                var docName= db.doctors.FirstOrDefault(c => c.Id == doctorId).doctorName;
                //emaiiil


                //Create a new MailMessage object
                try
                {



               
               MailMessage mail = new MailMessage();

                // Set the sender's email address
                mail.From = new MailAddress("musab.ghannam@outlook.com");

                // Set the recipient's email address

                mail.To.Add(docemail);

                // Set the subject of the email
                mail.Subject = "New message from " + "Finding piece";

                // Set the body of the email

                mail.Body = $"<b>Welcome to Finding Peace!</b><br/><br/>Dr-{docName}, your registration has been submitted and is waiting for approval. You will receive an email notification when your account has been accepted.";

                // Set the body format to HTML
                mail.IsBodyHtml = true;

                // Create a new SmtpClient object
                SmtpClient smtp = new SmtpClient("smtp-mail.outlook.com", 587);
                smtp.UseDefaultCredentials = false;
                smtp.Credentials = new NetworkCredential("musab.ghannam@outlook.com", "124816326455@Mo");
                smtp.EnableSsl = true;

                // Send the email
                smtp.Send(mail);
                }
                catch(Exception ex) { 




                
                
                }

                //email

                db.SaveChanges();

                doctor.statedoctor = 0;

                TempData["swal_message"] = $"Dr-{docName}\tYour registration has been submitted and is waiting for approval. You will receive an email notification when your account has been accepted.";
                ViewBag.title = "success";
                ViewBag.icon = "success";
                ViewBag.redirectUrl = Url.Action("Index", "mainHome");

                return View("EnrollDoctor", data);
            }



            data.Specializations = specializations;
            data.doc = doct;


            //data.doctor = doctors;


            return View("EnrollDoctor", data);



        }

        public ActionResult DoctorDashboard()
        {
           


            string zoomLink = Session["link"] as string;
            var mainId = User.Identity.GetUserId();



            var doctorId = db.doctors.FirstOrDefault(x => x.Id == mainId).doctorId;


            var appointment = db.appointments.Where(c => c.doctorId == doctorId).ToList();

mainMasterpiesce/mainMasterpiesce/Views/DoctorEnrolling/DoctorDashSetting.cshtml
@model Tuple<List<mainMasterpiesce.Models.doctor>, List<mainMasterpiesce.Models.appointment>, List<mainMasterpiesce.Models.feedback>>
@{
    ViewBag.Title = "DoctorDashSetting";
    Layout = "~/Views/Shared/_DoctorDashboard.cshtml";
}



<!-- Page Content -->




<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.6/dist/sweetalert2.min.css">
<div class="col-md-7 col-lg-8 col-xl-9">


    @using (Html.BeginForm("EditDoctor", "DoctorEnrolling", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {


        <!-- Basic Information -->
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Basic Information</h4>
                <div class="row form-row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <div class="change-avatar">
                                <div class="profile-img">
                                    <img src="@Url.Content(@Model.Item1[0].picdoctor)" alt="User Image">

                                </div>
                                <div class="upload-img">
                                    <div class="change-photo-btn">
                                        <span><i class="fa fa-upload"></i> Upload Photo</span>
                                        <input type="file" class="upload" name="profpic">
                                    </div>
                                    <small class="form-text text-muted">
                                        Allowed JPG, GIF or PNG. Max
                                        size of 2MB
                                    </small>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Username <span class="text-danger">*</span></label>

                            <input type="text" class="form-control" name="docname" value="@Model.Item1[0].doctorName">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Email <span class="text-danger">*</span></label>
                            <input type="email" class="form-control" name="email" value="@Model.Item1[0].AspNetUser.Email">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Phone Number <span class="text-danger">*</span></label>
                            <input type="text" class="form-control" name="phonenumb" value="@Model.Item1[0].AspNetUser.PhoneNumber">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Date Of Birth <span class="text-danger">*</span></label>
                            <input type="datetime" class="form-control" name="birth" value="@Model.Item1[0].birthday">
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Gender</label>
                            <select class="form-control select" name="gender">
                                <option>Select</option>

                                <option value="Male" @(Model.Item1[0].Gender == true ? "selected" : "")>Male</option>
                                <option value="Female" @(Model.Item1[0].Gender == false ? "selected" : "")>Female</option>

                            </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group mb-0">
                            <label>IBAN</label>
                            <input type="text" name="Iban" class="form-control" value="@Model.Item1[0].IBAN">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /Basic Information -->
        <!-- About Me -->
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">About Me</h4>
                <div class="form-group mb-0">
                    <label>Biography</label>
                    <textarea class="form-control" rows="5" name="info" value="@Model.Item1[0].infodoctor">@Model.Item1[0].infodoctor</textarea>
                </div>
            </div>
        </div>
        <!-- /About Me -->
        <!-- Clinic Info -->
        <!-- /Clinic Info -->
        <!-- Contact Details -->
        <div class="card contact-card">
            <div class="card-body">
                <h4 class="card-title">Contact Details</h4>
                <div class="row form-row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Address </label>
                            <input type="text" class="form-control" name="address" value="@Model.Item1[0].addresss">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label">Lcation Link</label>
                            <input type="text" class="form-control" name="locationLink" value="@Model.Item1[0].locationdoctor.Split('_')[1]">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label">City</label>
                            <input type="text" class="form-control" name="city" value="@Model.Item1[0].locationdoctor.Split('_')[0].Split(',')[0]">
                        </div>
                    </div>

                    @*<div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label">State / Province</label>
                            <input type="text" class="form-control">
                        </div>
                    </div>*@
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label">Country</label>
                            <input type="text" class="form-control" name="country" value="@Model.Item1[0].locationdoctor.Split('_')[0].Split(',')[1]">
                        </div>
                    </div>
                    @*<div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label">Postal Code</label>
                            <input type="text" class="form-control">
                        </div>
                    </div>*@
                </div>
            </div>
        </div>
        <!-- /Contact Details -->
        <!-- Pricing -->
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Price per hour</h4>

                <div class="form-group mb-0">
                    <div id="pricing_select">
                        <div class="custom-control custom-radio custom-control-inline">

                        </div>
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="text" class="form-control" name="price" value="@Model.Item1[0].pricePerHour">

                        </div>
                    </div>

                </div>

                <div class="row custom_price_cont" id="custom_price_cont" style="display: none;">
                    <div class="col-md-4">
                        <input type="text" class="form-control" id="custom_rating_input"
                               name="custom_rating_count" value="" placeholder="20">
                        <small class="form-text text-muted">Custom price you can add</small>
                    </div>
                </div>

            </div>
        </div>
        <!-- /Pricing -->
        <!-- Services and Specialization -->
        <div class="card services-card">
            <div class="card-body">
                <h4 class="card-title"> Specialization</h4>
                <div class="form-group">
                    <div class="form-group">
                        <label>Specialization </label>
                        <select class="form-control select" name="special">
                            <option>Select</option>

                            <option value="1" @(Model.Item1[0].specialization1.namespecialization == "Individual therapy" ? "selected" : "")>Individual therapy</option>
                            <option value="2" @(Model.Item1[0].specialization1.namespecialization == "Family therapy" ? "selected" : "")>Family therapy</option>
                            <option value="3" @(Model.Item1[0].specialization1.namespecialization == "Couple therapy" ? "selected" : "")>Couple therapy</option>



                            <option value="4" @(Model.Item1[0].specialization1.namespecialization == "Conselling therapy" ? "selected" : "")>Conselling therapy</option>




                        </select>
                    </div>

                </div>

            </div>
        </div>
        <!-- /Services and Specialization -->
        <!-- Education -->
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Education</h4>
                <div class="education-info">
                    <div class="row form-row education-cont">
                        <div class="col-12 col-md-10 col-lg-11">
                            <div class="row form-row">
                                <div class="col-12 col-md-6 col-lg-4">
                                    <div class="form-group">
                                        <label>Degree</label>
                                        <input type="text" class="form-control" value="@Model.Item1[0].educationdetails.Split('_')[0]" name="Degree">
                                    </div>
                                </div>
                                <div class="col-12 col-md-6 col-lg-4">
                                    <div class="form-group">
                                        <label>College/Institute</label>
                                        <input type="text" class="form-control" value="@Model.Item1[0].educationdetails.Split('_')[1]" name="college">
                                    </div>
                                </div>
                                <div class="col-12 col-md-6 col-lg-4">
                                    <div class="form-group">
                                        <label>Year of Completion</label>
                                        <input type="text" class="form-control" value="@Model.Item1[0].educationdetails.Split('_')[2]" name="yeargrad">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="add-more">
                    <a href="javascript:void(0);" class="add-education">
                        <i class="fa fa-plus-circle"></i> Add More
                    </a>
                </div>
            </div>
        </div>






        <div class="submit-section submit-btn-bottom">
            @*<button type="submit" class="btn btn-primary submit-btn">Save Changes</button>*@
            <input type="submit" class="btn btn-primary submit-btn" value="Save Changes" />

        </div>
    }
</div>



<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.6/dist/sweetalert2.all.min.js"></script>
@if (TempData["swal_message"] != null)
{
    <script>
        Swal.fire({
            title: "@ViewBag.title",
            text: "@TempData["swal_message"]",
            icon: "@ViewBag.icon",

             allowOutsideClick: false, // prevent clicking outside the dialog to close it
            allowEscapeKey: false // prevent pressing the escape key to close it


        }).then(function () {
            window.location.href = "DoctorDashSetting";

        });;
    </script>
}



<!-- /Page Content -->

mainMasterpiesce/mainMasterpiesce/Views/DoctorEnrolling/MyReviews.cshtml
@model Tuple<List<mainMasterpiesce.Models.doctor>, List<mainMasterpiesce.Models.appointment>, List<mainMasterpiesce.Models.feedback>>
@using System.Globalization;
@{
    ViewBag.Title = "MyReviews";
    Layout = "~/Views/Shared/_DoctorDashboard.cshtml";
}

<script src="https://kit.fontawesome.com/cd43dd9542.js" crossorigin="anonymous"></script>
<style>
  #accept{
      font-weight:bold;
      font-size:17px;

  }
</style>



<div class="col-md-7 col-lg-8 col-xl-9">

    <!-- Page Header -->
    <div class="page-header">
        <div class="row">
            <div class="col-sm-12">

                <ul class="breadcrumb">
                    <li id="accept"><a href="MyReviews">Accepted Reviews/</a></li>
                    <li id="reject"><a href="PendingReviews">Pending Reviews</a></li>
                </ul>



            </div>
        </div>
    </div>

    @*start acceptreviews*@
    <div class="doc-review review-listing appointments" id="previous-appointments">

        <!-- Review Listing -->
        <ul class="comments-list">

            <!-- Comment List -->
            @foreach (var comment in Model.Item3.Where(c => c.statefeedback == 1))
            {
               


                <li>


                    <div class="comment">
                        <img class="avatar rounded-circle" alt="User Image"
                             src="~/Content/images/@Url.Content(comment.patient.picpatient)">
                        <div class="comment-body">
                            <div class="meta-data">
                                <span class="comment-author">@comment.patient.patientName</span>
                                <span class="comment-date">


                                    Reviewed at  @comment.feedbacktime.Value.ToString("dd-MM-yyyy")


























                                </span>
                                <div class="review-count rating">
                                    @for (int i = 0; i < comment.rating; i++)
                                    {
                                        <i class="fas fa-star filled"></i>
                                    }
                                    @for (int i = 0; i < 5 - comment.rating; i++)
                                    {
                                        <i class="fas fa-star"></i>
                                    }


                                </div>
                            </div>
                            <p class="recommended">
                                <i class="far fa-thumbs-up"></i> I recommend the
                                doctor
                            </p>
                            <p class="comment-content">
                                @comment.comment
                            </p>
                            <div class="comment-reply">
                                <a class="comment-btn" href="#">

                                </a>
                                <p class="recommend-btn">
                                    <span>Accept?</span>
                                    @if (comment.statefeedback == 1)
                                    {









                                        <a href="~/DoctorEnrolling/samestate?id=@comment.feedbackId" class="like-btn" style="background-color:green;color:white">
                                            <i class="far fa-thumbs-up"></i> Yes
                                        </a>



                                        <a href="~/DoctorEnrolling/firstReject?id=@comment.feedbackId" class="dislike-btn">
                                            <i class="far fa-thumbs-down"></i> No
                                        </a>


                                    }
                      

                                </p>
                            </div>
                        </div>
                    </div>


                </li>
            }


        </ul>

        @if (Model.Item3.Where(c=>c.statefeedback==1).Count() == 0)
            {
            <h3 style="text-align:center;align-items:center;color:darkred">there is No Accepted Reviews Yet</h3>

            }

    </div>

    @*finish acceptreviews**@

</div>
<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.6/dist/sweetalert2.all.min.js"></script>

@if (TempData["swal_message"] == "Are you sure you want to disappear this Review?")
{
    <script>
        Swal.fire({
            title: "@ViewBag.title",
            text: "@TempData["swal_message"]",
            icon: "@ViewBag.icon",
            showCancelButton: true,
            confirmButtonText: "Confirm",
            cancelButtonText: "@ViewBag.cancelButton",
            allowOutsideClick: false, // prevent clicking outside the dialog to close it
            allowEscapeKey: false // prevent pressing the escape key to close it
        }).then((result) => {
            if (result.isConfirmed) {
                // User clicked "Confirm" button
                window.location.href = "/DoctorEnrolling/Block";
            } else if (result.dismiss === Swal.DismissReason.cancel) {
                // User clicked "Cancel" button
                // Do nothing or add additional behavior as needed
            }
        });
    </script>
}


@if (TempData["swal_message"] == "Are you sure you want to display this Review?")
{
    <script>
        Swal.fire({
            title: "@ViewBag.title",
            text: "@TempData["swal_message"]",
            icon: "@ViewBag.icon",
            showCancelButton: true,
            confirmButtonText: "Confirm",
            cancelButtonText: "@ViewBag.cancelButton",
            allowOutsideClick: false, // prevent clicking outside the dialog to close it
            allowEscapeKey: false // prevent pressing the escape key to close it
        }).then((result) => {
            if (result.isConfirmed) {
                // User clicked "Confirm" button
                window.location.href = "/DoctorEnrolling/Acceptt";
            } else if (result.dismiss === Swal.DismissReason.cancel) {
                // User clicked "Cancel" button
                // Do nothing or add additional behavior as needed
            }
        });
    </script>
}



@if (TempData["swal_message"] == "You cannot block this doctor. To block a doctor, they must have more than 10 appointments with a rating less than 2. Please try again.")
{
    <script>
          Swal.fire({
            title: "@ViewBag.title",
            text: "@TempData["swal_message"]",
            icon: "@ViewBag.icon",

             allowOutsideClick: false, // prevent clicking outside the dialog to close it
            allowEscapeKey: false // prevent pressing the escape key to close it


        }).then(function () {
            window.location.href = "AdminDoctor";

        });;
    </script>
}


@if (TempData["IsAccept"] == "samestate")
{
    <script>
        Swal.fire({
            title: "@ViewBag.title",
            text: "@TempData["swal_message"]",
            icon: "@ViewBag.icon",

             allowOutsideClick: false, // prevent clicking outside the dialog to close it
            allowEscapeKey: false // prevent pressing the escape key to close it


        }).then(function () {
            window.location.href = "MyReviews";

        });;
    </script>
}
<script>
    function toggleDisplay(idToShow) {
        var allElements = document.getElementsByClassName("appointments");
        for (var i = 0; i < allElements.length; i++) {
            var element = allElements[i];
            if (element.id === idToShow) {
                element.style.display = "block";
            } else {
                element.style.display = "none";
            }
        }

        // Apply styling to first link
        var firstLink = document.getElementById("prev");
        if (idToShow === "previous-appointments") {
            firstLink.style.fontWeight = "bold";
            firstLink.style.color = "red";
            firstLink.style.fontSize = "25px";
        } else {
            firstLink.style.fontWeight = "normal";
            firstLink.style.color = "inherit";
            firstLink.style.fontSize = "15px";
        }




        var sec = document.getElementById("upc");
        if (idToShow === "upcoming-appointments") {
            sec.style.fontWeight = "bold";
            sec.style.color = "red";
            sec.style.fontSize = "25px";
        } else {
            sec.style.fontWeight = "normal";
            sec.style.color = "inherit";
            sec.style.fontSize = "15px";
        }






    }


</script>