mainMasterpiesce/mainMasterpiesce/Models/doctor.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mainMasterpiesce.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doctor()
        {
            this.appointments = new HashSet<appointment>();
            this.feedbacks = new HashSet<feedback>();
            this.NotAvailableTimes = new HashSet<NotAvailableTime>();
            this.transactionsdoctors = new HashSet<transactionsdoctor>();
            this.patients = new HashSet<patient>();
        }
    
        public int doctorId { get; set; }
        public string Id { get; set; }
    
        public string locationdoctor { get; set; }

        public string doctorName { get; set; }
        public string email { get; set; }
        public string phoneNumber { get; set; }
        public string qualiification { get; set; }

        public string specialization { get; set; }
        public Nullable<System.DateTime> startedate { get; set; }
        public string idCardfile { get; set; }
        public string picdoctor { get; set; }
        public string certificationfile { get; set; }
        public string birthfile { get; set; }
        public Nullable<int> specializationId { get; set; }
        public Nullable<int> statedoctor { get; set; }
        public Nullable<double> earningDoctortotal { get; set; }
        public Nullable<double> AmountsDue { get; set; }
        public string IBAN { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string infodoctor { get; set; }
        public Nullable<double> pricePerHour { get; set; }
        public Nullable<double> ratingdoctor { get; set; }
        public Nullable<int> ratingint { get; set; }
        public string experience { get; set; }

        public Nullable<System.DateTime> birthday { get; set; }
        public string addresss { get; set; }
        public string educationdetails { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<appointment> appointments { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual specialization specialization1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<feedback> feedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotAvailableTime> NotAvailableTimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transactionsdoctor> transactionsdoctors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<patient> patients { get; set; }
    }
}

mainMasterpiesce/mainMasterpiesce/Controllers/doctorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using mainMasterpiesce.Models;
using System.IO.Compression;
using System.Web.Configuration;
using Microsoft.AspNet.Identity;
using System.Net.Mail;

namespace mainMasterpiesce.Controllers
{
    [Authorize(Roles = "Admin")]
    public class doctorsController : Controller
    {
        private FindingpeaceEntities1 db = new FindingpeaceEntities1();

        // GET: doctors
        public ActionResult 
            AdminDoctor(string id, string Block,string Accept,string idaccep,string search)
        {
            var appointmentsByPatient = db.appointments.GroupBy(c => c.doctorId).Count();
         
            
            ViewBag.sumprice=appointmentsByPatient; 
            var doctors = db.doctors.Include(d => d.AspNetUser).Include(d => d.specialization1);

            if (Block != null)
            {
                TempData["IdBLOCK"] = Convert.ToInt16(Block);


            }

            ViewBag.Block = false;
            if (TempData["IdBLOCK"] != null)
            {

                int doctorId = Convert.ToInt16(TempData["IdBLOCK"]);
                var appointment = db.appointments.Where(c => c.doctorId == doctorId).ToList();
                var rate = db.doctors.FirstOrDefault(c => c.doctorId == doctorId).ratingint;
                int countappoint = 0;
                foreach (var item in appointment)
                {
                    countappoint++;
                }

                if (countappoint >= 10 && rate <= 2)
                {

                    ViewBag.Block = true;

                }
                ViewBag.rate=rate;
                ViewBag.count=countappoint;

                if (Block != null&& ViewBag.Block ==true)
            {
                    TempData["IdBLOCK"] = Convert.ToInt16(Block);
                    // Define the sweet alert message and options
                    string sweetAlertMessage = "Are you sure you want to block this doctor?";
                string sweetAlertTitle = "Confirm Block";
                string sweetAlertIcon = "warning";
                string sweetAlertCancelButton = "Cancel";

                // Update the TempData and ViewBag variables
                TempData["swal_message"] = sweetAlertMessage;
                ViewBag.title = sweetAlertTitle;
                ViewBag.icon = sweetAlertIcon;
                ViewBag.cancelButton = sweetAlertCancelButton;


                }
                else if(Block != null && ViewBag.Block == false)
                {

                    TempData["swal_message"] = $"You cannot block this doctor. To block a doctor, they must have more than 10 appointments with a rating less than 2. Please try again.";
                    ViewBag.title = "warning";
                    ViewBag.icon = "warning";
                    ViewBag.massagee = "You cannot block this doctor. To block a doctor, they must have more than 10 appointments with a rating less than 2. Please try again.";


                }

       


              


            }

       


            if (Accept != null)
            {

                // Define the sweet alert message and options
                string sweetAlertMessage = "Are you sure you want to Accept this doctor?";
                string sweetAlertTitle = "Confirm Block";
                string sweetAlertIcon = "warning";
                string sweetAlertCancelButton = "Cancel";

                // Update the TempData and ViewBag variables
                TempData["swal_message"] = sweetAlertMessage;
                ViewBag.title = sweetAlertTitle;
                ViewBag.icon = sweetAlertIcon;
                ViewBag.cancelButton = sweetAlertCancelButton;
                TempData["Id"] = Convert.ToInt16(Accept);
                TempData["list"] = "Rejectlist";



            }

            if (!string.IsNullOrEmpty(search))
            {
                var searchh = db.doctors.Where(c => c.doctorName.Contains(search)).ToList();

                return View(searchh);

            }
            else
            {



                return View(doctors.ToList());
            }




        }

        public ActionResult Acceptlist([Bind(Include = "statedoctor")] doctor doctor, string Accept)
        {

            TempData["list"] = "Acceptlist";

            return RedirectToAction("AdminDoctor", new { listType = "Acceptlist" });

        }
        public ActionResult Rejectlist([Bind(Include = "statedoctor")] doctor doctor, string Accept)
        {

            TempData["list"] = "Rejectlist";


            return RedirectToAction("AdminDoctor", new { listType = "rejectlist" });


        }


        public ActionResult Acceptt([Bind(Include = "statedoctor")] doctor doctor, string Accept)
        {
            int docId = Convert.ToInt32(TempData["Id"]);

        
            var doctorr=db.doctors.FirstOrDefault(c=>c.doctorId== docId);
            
            doctorr.statedoctor = 1;
            doctorr.AspNetUser.PhoneNumberConfirmed= true;//accepted doctor
            db.Entry(doctorr).State = EntityState.Modified;

            //emaiiil
            try
            {


         
            var docName = db.doctors.FirstOrDefault(c => c.doctorId == docId).doctorName;
            var docemail = db.doctors.FirstOrDefault(c => c.doctorId == docId).email;

            // Create a new MailMessage object
            MailMessage mail = new MailMessage();

            // Set the sender's email address
            mail.From = new MailAddress("musab.ghannam@outlook.com");

            // Set the recipient's email address

            mail.To.Add(docemail);

            // Set the subject of the email
            mail.Subject = "New message from " + "Finding piece";

            // Set the body of the email
            mail.Body = $@"<html>
                  <body>
                      <p>Dear<b> Dr. {docName}<b>,</p>
                      <br/>
                      <p>Welcome to Finding Peace! We are thrilled to have you as part of our community of healthcare professionals dedicated to improving mental health and wellbeing for all.</p>
                      <br/>
                      <p><b>Congratulations</b> on completing your registration! We appreciate your commitment to joining us in this important mission, and we look forward to supporting you in your journey.</p>
                      <br/>
                      <p>After reviewing your experience and qualifications, we are confident that you will be an excellent addition to our network of providers.</p>
                      <br/>
                      <p>As a registered member of Finding Peace, you will have access to a wealth of resources, including our online forum where you can connect with other healthcare providers and share best practices, our library of educational materials to help you stay up-to-date on the latest research and trends, and much more.</p>
                      <br/>
                      <p>We hope that your experience with Finding Peace will be rewarding and fulfilling, and that you will find it to be a valuable tool in your practice.</p>
                      <br/>
                      <p>If you have any questions or concerns, please don't hesitate to reach out to us at support@findingpeace.com.</p>
                      <br/>
                      <p>Best regards,</p>
                      <p>The Finding Peace Team</p>
                  </body>
              </html>";


            // Set the body format to HTML
            mail.IsBodyHtml = true;

            // Create a new SmtpClient object
            SmtpClient smtp = new SmtpClient("smtp-mail.outlook.com", 587);
            smtp.UseDefaultCredentials = false;
            smtp.Credentials = new NetworkCredential("musab.ghannam@outlook.com", "124816326455@Mo");
            smtp.EnableSsl = true;

            // Send the email
            smtp.Send(mail);

            }
            //email
            catch (Exception ex)
            {


            }

            db.SaveChanges();
            TempData["list"] = "Rejectlist";
            return RedirectToAction("AdminDoctor");
          
          

        
        }

        public ActionResult Block( [Bind(Include = "statedoctor")] doctor doctor, string Accept)
        {

          int docId = Convert.ToInt32(TempData["IdBLOCK"]);  

                var doctorr = db.doctors.FirstOrDefault(c => c.doctorId == docId);
                doctorr.statedoctor = 0;

                db.Entry(doctorr).State = EntityState.Modified;




            //emaiiil
            try
            {


        

            var docName = db.doctors.FirstOrDefault(c => c.doctorId == docId).doctorName;
            var docemail = db.doctors.FirstOrDefault(c => c.doctorId == docId).email;

            // Create a new MailMessage object
            MailMessage mail = new MailMessage();

            // Set the sender's email address
            mail.From = new MailAddress("musab.ghannam@outlook.com");

            // Set the recipient's email address

            mail.To.Add(docemail);

            // Set the subject of the email
            mail.Subject = "New message from " + "Finding piece";

            // Set the body of the email
            mail.Body = @"<html>
                  <body>
                      <p>Dear Dr. {docName},</p>
                      <br/>
                      <p>We regret to inform you that we will be unable to continue working with you on Finding Peace. Despite many appointments, we have received poor ratings from patients who have seen you, and as a result, we have decided to block your account on our platform.</p>
                      <br/>

mainMasterpiesce/mainMasterpiesce/Views/doctors/AdminDoctor.cshtml
@model IEnumerable<mainMasterpiesce.Models.doctor>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminDashBoard.cshtml";
}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.6/dist/sweetalert2.min.css">
<script src="https://kit.fontawesome.com/cd43dd9542.js" crossorigin="anonymous"></script>




<style>

    .fa-file-zipper {
        font-size: 40px;
        text-align: center;
        align-items: center;
    }
</style>
@if (TempData["list"] != "Rejectlist")
{


    @section Content {
        <form action="AdminDoctor">
            <input type="text" class="form-control" placeholder="Search here" name="search">
            <button class="btn" type="submit"><i class="fa fa-search"></i></button>
        </form>
    }

}




<div class="page-wrapper">


    <div class="content container-fluid">

        <!-- Page Header -->
        <div class="page-header">
            <div class="row">
                <div class="col-sm-7 col-auto">



                    @if (TempData["list"] == "Rejectlist")
                    {


                        <h3 class="page-title">
                            Pending Doctors
                        </h3>

                    }
                    else
                    {
                        <h3 class="page-title">
                            Accepted Doctors
                        </h3>

                    }










                 
                </div>
                <div class="col-sm-5 col">


                </div>
            </div>
        </div>
        <!-- /Page Header -->
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">

                            @{
                                string q = Request.QueryString["listType"];
                                int test = 1;
                            }


                            @if (TempData["list"] == "Rejectlist"||q== "rejectlist")
                            {

                                test = 0;

                            }
                            else
                            {
                                test = 1;
                            }

                            @{ 


                                //                                if(q=="rejectlist")
                                //                                {

                                //                                    test = 0;
                                //}


                            }



                            <table class="datatable table table-hover table-center mb-0">
                                <thead>
                                    <tr>
                                        <th>Doctor Name</th>
                                        <th>All Documentations</th>

                                        <th>Earned</th>
                                        <th>Account Status</th>
                                        <th>rating</th>
                                        <th>#No. appointments</th>
                                        <th>Actions</th>

                                    </tr>
                                </thead>
                                <tbody>




                                    @foreach (var item in Model.Where(c => c.statedoctor == test))
                                    {


                                        <tr>
                                            <td>
                                                <h2 class="table-avatar">
                                                    <a href="Details?id=@item.doctorId" class="avatar avatar-sm mr-2"><img class="avatar-img rounded-circle" src="@Url.Content(item.picdoctor)" alt="@item.picdoctor"></a>
                                                    <a href="Details?id=@item.doctorId">Dr. @item.doctorName</a>


                                                </h2>
                                                @if (item.specialization1 != null)
                                                {
                                                    <p style="color:gray;margin-top:10px;font-size:15px">  @item.specialization1.namespecialization</p>

                                                }

                                            </td>

                                            <td>



                                                <a href="DownloadAll?id=@item.doctorId" download><i class="fa-solid fa-file-zipper"></i></a>










                                            </td>


                                            <td>

                                                @{
                                                    int numm = 0;

                                                    foreach (var numb in item.appointments.Where(c => c.doctorId == item.doctorId && c.confirmappointment == 2))
                                                    {
                                                        numm++;


                                                    }




                                                    double totalprice = numm * Convert.ToInt16(item.pricePerHour) * .95;


                                                    //double amountdoc = Convert.ToDouble(totalprice) * .95;
                                                }

                                                @totalprice  JD





                                            </td>

                                            <td>
                                                @*<div class="status-toggle">
                                                        <input type="checkbox" id="status_1" class="check" checked>
                                                        <label for="status_1" class="checktoggle">checkbox</label>
                                                    </div>*@

                                                @if (item.statedoctor == 1)
                                                {


                                                    <span class="badge badge-pill bg-success-light">Confirm</span>


                                                }
                                                else
                                                {

                                                    <span class="badge badge-pill bg-danger-light">Pending</span>
                                                }

                                            </td>




                                            <td>
                                                @{

                                                    var ratt = item.ratingint;


                                                }

                                                @if (ratt != null)
                                                {

                                                    @ratt

}
else
                {
                    <p>there is no rating yet</p>
                }



                                            </td>
                                            <td>
                                                @{
                                                    int num = 0;

                                                }
                                                @foreach (var numb in item.appointments)
                                                {
                                                    num++; 


                                                }

                                                @num

                                            </td>
                                            @using (Html.BeginForm("AdminDoctor", "doctors", new { id = item.Id }, FormMethod.Post))
                                            {

                                                <td>


                                                    @if (test == 0)
                                                    {

                                                        @Html.ActionLink("Details", "Details", new { id = item.doctorId, listType = "rejectlist" }, new { @class = "btn btn-info" })


                                                    }
                                                    else
                                                    {

                                                        @Html.ActionLink("Details", "Details", new { id = item.doctorId }, new { @class = "btn btn-info" })

                                                    }






                                                    @*@Html.ActionLink("Details", "Details", new { id = item.doctorId }, new { @class = "btn btn-info" })*@
                                                    @Html.ActionLink("Delete", "Delete", new { id = item.doctorId }, new { @class = "btn btn-danger", onclick = "return confirm('Are you sure you want to delete this item?');" })







                                                    @if (item.statedoctor == 1)
                                                    {



                                                        <input type="hidden" name="Block" value="@item.doctorId" />



                                                        <input type="submit" name="Block" class="btn btn-danger" value="Block" />





                                                    }
                                                    else
                                                    {
                                                        <input type="hidden" name="Accept" value="@item.doctorId" />

                                                        <input type="submit" name="Accept" class="btn btn-primary" value="Accept" />
                                                    }



                                                </td>

                                            }

                                        </tr>
                                    }

                                </tbody>
                            </table>
























                        </div>
                    </div>
                </div>
            </div>
            <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
            <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.6/dist/sweetalert2.all.min.js"></script>
















            @if (TempData["swal_message"] == "Are you sure you want to block this doctor?")
            {
                <script>
        Swal.fire({
            title: "@ViewBag.title",
            text: "@TempData["swal_message"]",
            icon: "@ViewBag.icon",
            showCancelButton: true,
            confirmButtonText: "Confirm",
            cancelButtonText: "@ViewBag.cancelButton",
            allowOutsideClick: false, // prevent clicking outside the dialog to close it
            allowEscapeKey: false // prevent pressing the escape key to close it
        }).then((result) => {
            if (result.isConfirmed) {
                // User clicked "Confirm" button
                window.location.href = "/doctors/Block";
            } else if (result.dismiss === Swal.DismissReason.cancel) {
                // User clicked "Cancel" button
                // Do nothing or add additional behavior as needed
            }
        });
                </script>
            }


            @if (TempData["swal_message"] == "Are you sure you want to Accept this doctor?")
            {
                <script>
        Swal.fire({
            title: "@ViewBag.title",
            text: "@TempData["swal_message"]",
            icon: "@ViewBag.icon",
            showCancelButton: true,
            confirmButtonText: "Confirm",
            cancelButtonText: "@ViewBag.cancelButton",
            allowOutsideClick: false, // prevent clicking outside the dialog to close it
            allowEscapeKey: false // prevent pressing the escape key to close it
        }).then((result) => {
            if (result.isConfirmed) {
                // User clicked "Confirm" button
                window.location.href = "/doctors/Acceptt";
            } else if (result.dismiss === Swal.DismissReason.cancel) {
                // User clicked "Cancel" button
                // Do nothing or add additional behavior as needed
            }
        });
                </script>
            }


            @if (TempData["swal_message"] == "You cannot block this doctor. To block a doctor, they must have more than 10 appointments with a rating less than 2. Please try again.")
            {
                <script>
          Swal.fire({
            title: "@ViewBag.title",
            text: "@TempData["swal_message"]",
            icon: "@ViewBag.icon",

             allowOutsideClick: false, // prevent clicking outside the dialog to close it
            allowEscapeKey: false // prevent pressing the escape key to close it


        }).then(function () {
            window.location.href = "AdminDoctor";

        });;
                </script>
            }